#!/bin/sh
DIR=/home/pi/LocControl
SCRIPT="$DIR/LocControl.py"
LOG="$DIR/console.log"
LOCKDIR="/tmp/LocControl/"
export LOCCONTROL_RUNNINGDIR="/tmp/LocControl_Running/"

if ! mkdir "$LOCKDIR"; then
    echo "PID $$: could not create lock dir" >> $LOG
    exit 1
fi

cleanup () {
    if [ -d "$LOCKDIR" ] && ! rmdir "$LOCKDIR"; then
        echo "PID $$: could not remove lock dir" >> $LOG
    fi
    if [ -d "$LOCCONTROL_RUNNINGDIR" ] && ! rmdir "$LOCCONTROL_RUNNINGDIR"; then
        echo "PID $$: could not remove running dir" >> $LOG
    fi
    exit 0
}

run_script () {
    if [ -d "$LOCCONTROL_RUNNINGDIR" ] && ! rmdir "$LOCCONTROL_RUNNINGDIR"; then
        echo "PID $$: could not remove running dir"
    fi
    date
    echo "PID: $$"
    /usr/bin/python3.5 -u "$SCRIPT" $1
    return $?
} > $LOG 2>&1

trap "cleanup" INT TERM HUP EXIT
run_script
result=$?
while [ $result -ne 0 ]; do
    echo "Program exited with code $result, saving crash log." >> $LOG
    cp "$LOG" "$DIR/crash_$(date '+%Y-%m-%d_%H:%M:%S').log"
    if [ -d "$LOCCONTROL_RUNNINGDIR" ]; then
      run_script -autostart
      result=$?
    else
      result=0
    fi
done